/*******************************************/
/*     FILE GENERATED BY iec2c             */
/* Editing this file is not recommended... */
/*******************************************/

#include "iec_std_lib.h"

#include "accessor.h"

#include "POUS.h"

// CONFIGURATION CONF

void SRC_init__(void);

void config_init__(void) {
  BOOL retain;
  retain = 0;
  
  SRC_init__();
}

void SRC_run__(unsigned long tick);

void config_run__(unsigned long tick) {
  SRC_run__(tick);
}
unsigned long long common_ticktime__ = 4000000ULL; /*ns*/
unsigned long greatest_tick_count__ = (unsigned long)0UL; /*tick*/
