
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef OD_0_0_H
#define OD_0_0_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 OD_0_0_valueRangeTest (UNS8 typeValue, void * value);
const indextable * OD_0_0_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks);

/* Master node data struct */
extern CO_Data OD_0_0_Data;
extern UNS8 Can_Bitrate;		/* Mapped at index 0x4000, subindex 0x00*/
extern UNS8 SYS_TICK_PERIOD_MS;		/* Mapped at index 0x4001, subindex 0x00*/
extern UNS8 Axis_Number;		/* Mapped at index 0x4002, subindex 0x00*/
extern UNS8 Axis_Types[26];		/* Mapped at index 0x4003, subindex 0x01 - 0x1A */
extern REAL32 Axis_Mods[26];		/* Mapped at index 0x4004, subindex 0x01 - 0x1A */
extern UNS8 Axis_Reverses[26];		/* Mapped at index 0x4005, subindex 0x01 - 0x1A */
extern UNS32 HIO_compositions[4];		/* Mapped at index 0x4006, subindex 0x01 - 0x04 */
extern UNS32 Absolute_Encoder_Origins[26];		/* Mapped at index 0x4007, subindex 0x01 - 0x1A */
extern UNS8 TargetModes[26];		/* Mapped at index 0x4008, subindex 0x01 - 0x1A */
extern UNS8 ActualModes[26];		/* Mapped at index 0x4009, subindex 0x01 - 0x1A */
extern UNS16 Interpolation_data_records_low[26];		/* Mapped at index 0x4010, subindex 0x01 - 0x1A */
extern UNS16 Interpolation_data_records_high[26];		/* Mapped at index 0x4011, subindex 0x01 - 0x1A */
extern UNS16 ControlWords[26];		/* Mapped at index 0x4012, subindex 0x01 - 0x1A */
extern UNS16 Position_Actual_Low[26];		/* Mapped at index 0x4013, subindex 0x01 - 0x1A */
extern UNS16 Position_Actual_High[26];		/* Mapped at index 0x4014, subindex 0x01 - 0x1A */
extern UNS16 StatusWords[26];		/* Mapped at index 0x4015, subindex 0x01 - 0x1A */
extern INTEGER16 TargetTorques[26];		/* Mapped at index 0x4016, subindex 0x01 - 0x1A */
extern INTEGER16 TorqueOffsets[26];		/* Mapped at index 0x4017, subindex 0x01 - 0x1A */
extern INTEGER16 ActualTorques[26];		/* Mapped at index 0x4018, subindex 0x01 - 0x1A */
extern INTEGER16 ActualCurrents[26];		/* Mapped at index 0x4019, subindex 0x01 - 0x1A */
extern REAL32 Max_accelerations_mm_s_2[26];		/* Mapped at index 0x4020, subindex 0x01 - 0x1A */
extern REAL32 Max_Decelerations_mm_s[26];		/* Mapped at index 0x4021, subindex 0x01 - 0x1A */
extern REAL32 Max_Velocitys_mm_s[26];		/* Mapped at index 0x4022, subindex 0x01 - 0x1A */
extern REAL32 Max_Jerks_mm_s_3[26];		/* Mapped at index 0x4023, subindex 0x01 - 0x1A */
extern INTEGER16 Max_Torques[26];		/* Mapped at index 0x4024, subindex 0x01 - 0x1A */
extern UNS32 Position_Factor_Numerators[26];		/* Mapped at index 0x4030, subindex 0x01 - 0x1A */
extern UNS32 Position_Factor_Feed_Constants_Pulses[26];		/* Mapped at index 0x4031, subindex 0x01 - 0x1A */
extern REAL32 Soft_Limit_Low_mm[26];		/* Mapped at index 0x4040, subindex 0x01 - 0x1A */
extern REAL32 Soft_Limit_High_mm[26];		/* Mapped at index 0x4041, subindex 0x01 - 0x1A */
extern REAL32 Nature_Frequencys[26];		/* Mapped at index 0x4050, subindex 0x01 - 0x1A */
extern REAL32 Damp_Ratios[26];		/* Mapped at index 0x4051, subindex 0x01 - 0x1A */
extern UNS8 Modbus_Bitrate;		/* Mapped at index 0x4100, subindex 0x00*/
extern UNS16 Modbus_Coils[4];		/* Mapped at index 0x4110, subindex 0x01 - 0x04 */
extern UNS16 HIO_Input_Bools[8];		/* Mapped at index 0x4120, subindex 0x01 - 0x08 */
extern UNS16 HIO_Output_Bools[8];		/* Mapped at index 0x4121, subindex 0x01 - 0x08 */
extern UNS16 HIO_Input_Integers[32];		/* Mapped at index 0x4122, subindex 0x01 - 0x20 */
extern UNS16 HIO_Output_Integers[32];		/* Mapped at index 0x4123, subindex 0x01 - 0x20 */
extern UNS64 Ecat_Slave_Inputs[32];		/* Mapped at index 0x4130, subindex 0x01 - 0x20 */
extern UNS64 Ecat_Slave_Outputs[32];		/* Mapped at index 0x4131, subindex 0x01 - 0x20 */
extern UNS16 NCUC_Frames_1[20];		/* Mapped at index 0x4140, subindex 0x01 - 0x14 */
extern UNS16 NCUC_Frames_2[20];		/* Mapped at index 0x4141, subindex 0x01 - 0x14 */
extern UNS16 NCUC_Frames_3[20];		/* Mapped at index 0x4142, subindex 0x01 - 0x14 */
extern UNS16 NCUC_Frames_4[20];		/* Mapped at index 0x4144, subindex 0x01 - 0x14 */
extern REAL32 Group_Max_Accelerations_mm_s_2[2];		/* Mapped at index 0x4200, subindex 0x01 - 0x02 */
extern REAL32 Group_Max_Velocitys_mm_s[2];		/* Mapped at index 0x4202, subindex 0x01 - 0x02 */

#endif // OD_0_0_H
