/**
 * Code common to all C targets
 **/

#define _GNU_SOURCE

#include "iec_types.h"
/*
 * Prototypes of functions provided by generated C softPLC
 **/
void config_run__(unsigned long tick);
void config_init__(void);

/*
 * Prototypes of functions provided by generated target C code
 * */

void __init_debug(void);
void __cleanup_debug(void);
/*void __retrieve_debug(void);*/
void __publish_debug(void);
//#endif
/*
 *  Variables used by generated C softPLC and plugins
 **/
IEC_TIME __CURRENT_TIME;
IEC_BOOL __DEBUG = 0;
//#endif
unsigned long __tick = 0;

/*
 *  Variable generated by C softPLC and plugins
 **/
extern unsigned long greatest_tick_count__;
/* Help to quit cleanly when init fail at a certain level */
static int init_level = 0;

/*
 * Prototypes of functions exported by plugins
 **/
int __init_0();
void __cleanup_0(void);
void __retrieve_0(void);
void __publish_0(void);
int __init_1();
void __cleanup_1(void);
void __retrieve_1(void);
void __publish_1(void);

/*
 * Retrieve input variables, run PLC and publish output variables
 **/


void __run(void)
{

    __retrieve_0();
    __retrieve_1();

    /*__retrieve_debug();*/

#ifdef WIN32R
    PLC_GetTimeNow(&time_now);
    PLC_TimeDelay(&__CURRENT_TIME,&time_elapsed);
    HOTKEY_F5 = GetKeyState(VK_F5);
    if(debug_state==1)
    {
		__tick++;
		if (greatest_tick_count__)
        __tick %= greatest_tick_count__;
        config_run__(__tick);
    }
    else
	{
		if( HOTKEY_F5<0 && !debug_step_in)
		{
			config_run__(__tick);
			debug_step_in = 1;
		}
		else
		{
			PLC_TimeMinus(&time_now,&time_last,&time_elasped_tmp);
			PLC_TimeAdd(&time_elapsed,&time_elasped_tmp,&time_elapsed);
			debug_step_in = 0;
		}
    }
    time_last.tv_sec = time_now.tv_sec;
    time_last.tv_nsec = time_now.tv_nsec;  
#else
    __tick++;
    if (greatest_tick_count__)
        __tick %= greatest_tick_count__;
    config_run__(__tick);
#endif
    __publish_debug();
    __publish_1();
    __publish_0();
}

/*
 * Initialize variables according to PLC's default values,
 * and then init plugins with that values
 **/
int __init()
{
    int res = 0;
    init_level = 0;
    config_init__();
    __init_debug();
    init_level=1; if((res = __init_0())){return res;}
    init_level=2; if((res = __init_1())){return res;}
    return res;
}
/*
 * Calls plugin cleanup proc.
 **/
void __cleanup(void)
{
    if(init_level >= 2) __cleanup_1();
    if(init_level >= 1) __cleanup_0();
    __cleanup_debug();
}

#ifdef WIN32R
void PLC_GetTime(IEC_TIME *CURRENT_TIME);
void PLC_SetTimer(unsigned long long next, unsigned long long period);

#define CALIBRATED -2
#define NOT_CALIBRATED -1
static int calibration_count = NOT_CALIBRATED;
static IEC_TIME cal_begin;
static long long Tsync = 0;
static long long FreqCorr = 0;
static int Nticks = 0;
static unsigned long last_tick = 0;
static long long Ttick = 0;
#define mod %
#endif
/**
 * Prototypes for function provided by arch-specific code (main)
 * is concatained hereafter
 **/
//2021.3.10 ECAT 0.2
///////////////////////////////////////////////////////////////////////
#include <semaphore.h>
#include <errno.h>
#include <signal.h>
#include <stdio.h>
#include <string.h>
#include <sys/resource.h>
#include <sys/time.h>
#include <sys/types.h>
#include <unistd.h>
#include <sys/mman.h>
#include <pthread.h>

#include "iec_types.h"
#include <stdlib.h>
#include <netdb.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include "ecrt.h"
#include "OD_0_0.h"


UNS8 send_consise_dcf(CO_Data* d, UNS8 nodeId,ec_slave_config_t *sc);
static int run = 1;

extern UNS16 OD_0_0_highestSubIndex_obj4111;
void StartMb()
{
	OD_0_0_highestSubIndex_obj4111=1000;
	mbstart(520);
}

/****************************************************************************/
void signal_handler(int sig)
{
    printf("Deleting realtime task...\n");
	run = 0;
    knm_close2();
}
void signal_handler2(int sig)
{
    run = 1;
}

#define UINT8 	unsigned char
#define UINT16 	unsigned short int
#define UINT32 	unsigned int

//#define ENABLE_SIGNAL
//#define ENABLE_SENBUF

UINT16 receive_data[128];
UINT16 send_data[128];
UINT16 receive_size;
UINT16 send_size;
UINT16 packet_num;

UINT8 get_packet_num(void)
{
		UINT32 tmp_data;
        packet_num = tmp_data&0xff;
}

///////////////////////////////////////////////////////////////////////
IEC_TIME __CURRENT_TIME;
extern unsigned long long common_ticktime__;
extern unsigned long __tick;

#include <time.h>

//static long long Ttick = 0;
void PLC_GetTime(IEC_TIME *CURRENT_TIME)
{
    unsigned long long timenow;
    timenow = rt_timer_read();
    CURRENT_TIME->tv_sec = timenow / 1000000000;
    CURRENT_TIME->tv_nsec = timenow % 1000000000;	
}
void PLC_SetTimer(unsigned long long next, unsigned long long period)
{
  //RTIME current_time = rt_timer_read();
//  rt_task_set_periodic(&main_task, current_time + next, rt_timer_ns2ticks(period));
}

void plc_run()
{
    PLC_GetTime(&__CURRENT_TIME);
    __run();
}

extern int TSK2;

int create_tasks()
{
    struct timespec wakeup;
    clock_gettime(CLOCK_MONOTONIC, &wakeup);

    while (1) {
        wakeup.tv_nsec += 4000000;
        if (wakeup.tv_nsec >= 1000000000L) {
            wakeup.tv_nsec -= 1000000000L;
            wakeup.tv_sec++;
        }
        clock_nanosleep(CLOCK_MONOTONIC, TIMER_ABSTIME, &wakeup, NULL);
        TSK2 =1;
        plc_run();
    }
}
//#include "task.c"
#include <fcntl.h>
/////////////////////////////////////////////////////////////////////////
//RT_TASK bus_task;

int plcstart()
{
	int ret,i;

  
////////////////////////////////////////////////////////////////////
	/* Perform auto-init of rt_print buffers if the task doesn't do so */
    signal(SIGTERM, signal_handler);
    signal(SIGINT, signal_handler);
	signal(SIGHUP,signal_handler2);

    mlockall(MCL_CURRENT | MCL_FUTURE);
    struct sched_param sp = { .sched_priority = sched_get_priority_max(SCHED_FIFO) };
    pthread_setschedparam(pthread_self(), SCHED_FIFO, &sp);

    printf("Requesting master...\n");
//	sleep(1);
 	__init();
	StartMb();
/////////////////////////////////////////////
create_tasks();	

    return 0;
}