/**
 * Code common to all C targets
 **/

#define _GNU_SOURCE

#include "iec_types.h"
#include <elog.h>
#include <elog_file.h>

/*
 * Prototypes of functions provided by generated C softPLC
 **/
void config_run__(unsigned long tick);
void config_init__(void);

/*
 * Prototypes of functions provided by generated target C code
 * */

void __init_debug(void);
void __cleanup_debug(void);
/*void __retrieve_debug(void);*/
void __publish_debug(void);
//#endif
/*
 *  Variables used by generated C softPLC and plugins
 **/
IEC_TIME __CURRENT_TIME;
IEC_BOOL __DEBUG = 0;
//#endif
unsigned long __tick = 0;

/*
 *  Variable generated by C softPLC and plugins
 **/
extern unsigned long greatest_tick_count__;
/* Help to quit cleanly when init fail at a certain level */
static int init_level = 0;

/*
 * Prototypes of functions exported by plugins
 **/
int __init_0();
void __cleanup_0(void);
void __retrieve_0(void);
void __publish_0(void);
int __init_1();
void __cleanup_1(void);
void __retrieve_1(void);
void __publish_1(void);

/*
 * Retrieve input variables, run PLC and publish output variables
 **/


void __run(void)
{

    __retrieve_0();
    __retrieve_1();

    /*__retrieve_debug();*/
    __tick++;
    if (greatest_tick_count__)
        __tick %= greatest_tick_count__;
    config_run__(__tick);
    __publish_debug();
    __publish_1();
    __publish_0();
}

/*
 * Initialize variables according to PLC's default values,
 * and then init plugins with that values
 **/
int __init()
{
    int res = 0;
    init_level = 0;
    config_init__();
    __init_debug();
    init_level=1; if((res = __init_0())){return res;}
    init_level=2; if((res = __init_1())){return res;}
    return res;
}
/*
 * Calls plugin cleanup proc.
 **/
void __cleanup(void)
{
    if(init_level >= 2) __cleanup_1();
    if(init_level >= 1) __cleanup_0();
    __cleanup_debug();
}

#ifdef WIN32R
void PLC_GetTime(IEC_TIME *CURRENT_TIME);
void PLC_SetTimer(unsigned long long next, unsigned long long period);

#define CALIBRATED -2
#define NOT_CALIBRATED -1
static int calibration_count = NOT_CALIBRATED;
static IEC_TIME cal_begin;
static long long Tsync = 0;
static long long FreqCorr = 0;
static int Nticks = 0;
static unsigned long last_tick = 0;
static long long Ttick = 0;
#define mod %
#endif
/**
 * Prototypes for function provided by arch-specific code (main)
 * is concatained hereafter
 **/
//2021.3.10 ECAT 0.2
///////////////////////////////////////////////////////////////////////
#include <semaphore.h>
#include <errno.h>
#include <signal.h>
#include <stdio.h>
#include <string.h>
#include <sys/resource.h>
#include <sys/time.h>
#include <sys/types.h>
#include <unistd.h>
#include <sys/mman.h>
#include <pthread.h>

#include "iec_types.h"
#include <stdlib.h>
#include <netdb.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include "ecrt.h"
//#include "OD_0_0.h"


static int run = 1;

void StartMb()
{
	mbstart(520);
}

/****************************************************************************/
void signal_handler(int sig)
{
    printf("Deleting realtime task...\n");
	run = 0;
    //knm_close2();
}
void signal_handler2(int sig)
{
    run = 1;
}

#define UINT8 	unsigned char
#define UINT16 	unsigned short int
#define UINT32 	unsigned int

//#define ENABLE_SIGNAL
//#define ENABLE_SENBUF

UINT16 receive_data[128];
UINT16 send_data[128];
UINT16 receive_size;
UINT16 send_size;
UINT16 packet_num;

UINT8 get_packet_num(void)
{
		UINT32 tmp_data;
        packet_num = tmp_data&0xff;
}

///////////////////////////////////////////////////////////////////////
IEC_TIME __CURRENT_TIME;
extern unsigned long long common_ticktime__;
extern unsigned long __tick;

#include <time.h>

//static long long Ttick = 0;
void PLC_GetTime(IEC_TIME *CURRENT_TIME)
{
    //unsigned long long timenow;
    //timenow = rt_timer_read();
    //CURRENT_TIME->tv_sec = timenow / 1000000000;
    //CURRENT_TIME->tv_nsec = timenow % 1000000000;
    struct timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    CURRENT_TIME->tv_sec = ts.tv_sec;
    CURRENT_TIME->tv_nsec = ts.tv_nsec;
}
void PLC_SetTimer(unsigned long long next, unsigned long long period)
{
  //RTIME current_time = rt_timer_read();
//  rt_task_set_periodic(&main_task, current_time + next, rt_timer_ns2ticks(period));
}

void plc_run()
{
    PLC_GetTime(&__CURRENT_TIME);
	//log_i("clock_gettime%ld,%ld",__CURRENT_TIME.tv_sec,__CURRENT_TIME.tv_nsec);
    __run();
}


int create_tasks()
{
    struct timespec wakeup;
    clock_gettime(CLOCK_MONOTONIC, &wakeup);

    while (1) {
        wakeup.tv_nsec += 4000000;
        if (wakeup.tv_nsec >= 1000000000L) {
            wakeup.tv_nsec -= 1000000000L;
            wakeup.tv_sec++;
        }
        clock_nanosleep(CLOCK_MONOTONIC, TIMER_ABSTIME, &wakeup, NULL);
        plc_run();
    }
}
//#include "task.c"
#include <fcntl.h>
/////////////////////////////////////////////////////////////////////////
//RT_TASK bus_task;
int initelog()
{
	elog_init();
	ElogFileCfg cfg = {"cf.log", 10*1024*1024, 10};
    elog_file_config(&cfg);
    elog_file_init();
	elog_set_text_color_enabled(0);
    elog_set_terminal_enabled(0);
    elog_set_fmt(ELOG_LVL_ERROR, ELOG_FMT_TIME|ELOG_FMT_LINE);
    elog_set_fmt(ELOG_LVL_INFO, ELOG_FMT_LVL);
	elog_set_fmt(ELOG_LVL_WARN, ELOG_FMT_LVL);
	elog_set_fmt(ELOG_LVL_ASSERT, ELOG_FMT_LVL);
	elog_set_fmt(ELOG_LVL_VERBOSE, ELOG_FMT_LVL);
	elog_set_fmt(ELOG_LVL_DEBUG, ELOG_FMT_LVL|ELOG_FMT_LINE);
elog_start();
	
}
int main1()
{
	int ret,i;
    signal(SIGTERM, signal_handler);
    signal(SIGINT, signal_handler);
	signal(SIGHUP,signal_handler2);

    mlockall(MCL_CURRENT | MCL_FUTURE);
    struct sched_param sp = { .sched_priority = sched_get_priority_max(SCHED_FIFO) };
    pthread_setschedparam(pthread_self(), SCHED_FIFO, &sp);

    printf("Requesting master...\n");
//	sleep(1);
 	__init();
	StartMb();
/////////////////////////////////////////////
create_tasks();	

    return 0;
}


/* PDO 输出偏移 */
void plcrun();
#define FREQ_HZ        1000
#define PERIOD_NS      (1000000000L / FREQ_HZ)
int main(void)
{
    //实时化 
    mlockall(MCL_CURRENT | MCL_FUTURE);
    struct sched_param sp = { .sched_priority = sched_get_priority_max(SCHED_FIFO) };
    pthread_setschedparam(pthread_self(), SCHED_FIFO, &sp);
initelog();
    /* 请求主站与域 */
__init();
StartMb();
    puts("EK1100+EL2008 PREEMPT_RT demo running at 1 kHz ...");

    struct timespec wakeup;
    clock_gettime(CLOCK_MONOTONIC, &wakeup);
    while (1) {
        // 1 kHz 绝对周期 
        wakeup.tv_nsec += PERIOD_NS;
        if (wakeup.tv_nsec >= 1000000000L) {
            wakeup.tv_nsec -= 1000000000L;
            wakeup.tv_sec++;
        }
        clock_nanosleep(CLOCK_MONOTONIC, TIMER_ABSTIME, &wakeup, NULL);
		plc_run();
    }
    return 0;
}
