/*******************************************/
/*     FILE GENERATED BY iec2c             */
/* Editing this file is not recommended... */
/*******************************************/

#include "iec_std_lib.h"

// RESOURCE SRC

extern unsigned long long common_ticktime__;

#include "accessor.h"
#include "POUS.h"

#include "conf.h"
__DECLARE_GLOBAL(BOOL,SRC,GINIT)
__DECLARE_GLOBAL(PYGT,SRC,PYG)

#include "POUS.c"

BOOL TSK;
MAIN_FBD SRC__REF;
#define REF SRC__REF

void SRC_init__(void) {
  BOOL retain;
  retain = 0;
  __INIT_GLOBAL(BOOL,GINIT,__INITIAL_VALUE(__BOOL_LITERAL(FALSE)),retain)
  __INIT_GLOBAL(PYGT,PYG,__INITIAL_VALUE({0,10.0}),retain)
  TSK = __BOOL_LITERAL(FALSE);
  MAIN_FBD_init__(&REF,retain);
}

void SRC_run__(unsigned long tick) {
  //TSK = !(tick % 1);
  MAIN_FBD_body__(&REF);
}

