/*******************************************/
/*     FILE GENERATED BY iec2c             */
/* Editing this file is not recommended... */
/*******************************************/

#include "iec_std_lib.h"

// RESOURCE SRC

extern unsigned long long common_ticktime__;

#include "accessor.h"
#include "POUS.h"

#include "conf.h"
__DECLARE_GLOBAL(BOOL,SRC,GINIT)

#include "POUS.c"

BOOL TSK2;
IDLE SRC__REF3;
#define REF3 SRC__REF3

void SRC_init__(void) {
  BOOL retain;
  retain = 0;
  __INIT_GLOBAL(BOOL,GINIT,__INITIAL_VALUE(__BOOL_LITERAL(FALSE)),retain)
  TSK2 = __BOOL_LITERAL(FALSE);
  IDLE_init__(&REF3,retain);
}

void SRC_run__(unsigned long tick) {
//  TSK2 = !(tick % 1);
  if (TSK2) {
TSK2 = 0;
    IDLE_body__(&REF3);
  }
}

